# Generated by Django 5.0.4 on 2024-04-14 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_user_address_user_location_user_pincode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='quantity',
        ),
    ]
